database:
  type: "MYSQL"

bungeecord:
  enable: true
  kick-whitout-using-correct-ip: "&cPlease, use the correct ip of the server to connect on it."
  move-to-hub-at-restart: false
  hub-instance: "hub"
  whitelist:
    - "172.93.104.4"
    
namemc:
  check-enabled: true
  server-ip: "akyto.club"
  like-tag: "&c❤"
    
chat:
  format: "%prefix%%rankColor%%player%%likeTag%&7: &f%msg%"
  staff-format: "&7[&eStaff&7] %prefix%%rankColor%%player%&7: &e%msg%"
  staff-symbol: "!"
  state: "GLOBAL"
  cooldown:
    enabled: true
    message: "&cPlease wait &f%time% second(s) &cto send another message!"
    priority: "NORMAL"
  filtered: ["ntm", "fdp", "kys", "nigger", "hitler", "staline", "nigga", "negga", "nig", "faggot"]
  
autoclicker:
  max-cps: 20
  
freeze:
  movement-message:
    - "&7&m---------------------------"
    - "&fYou've been frozen by a staff member!"
    - "&ePlease join our discord: &chttps://discord.gg/BRwRRarRYR/"
    - "&7&m---------------------------"
  disconnect-ban: true
  open-inventory: true
  inventory:
    item: "PACKED_ICE"
    title: "&7Frozen »"
    display: "&7Your are currently frozen."
    lore:
      - "&7&m---------------------"
      - "&7Please join our &fDiscord"
      - "&c.gg/BRwRRarRYR"
      - "&7&m---------------------"

permissions:
  staff-announce: "akyto.staff"
  rank-admin: "akyto.rank.admin"
  rank-up: "akyto.rank.up"
  rank-down: "akyto.rank.down"
  addBan: "akyto.ban"
  removeBan: "akyto.unban"
  view-cps: "akyto.staff"
  chat-cooldown-bypass: "akyto.chat.cooldown.bypass"
  chat-filter-bypass: "akyto.chat.filter.bypass"
  chat-clear: "akyto.chat.clear"
  chat-manage: "akyto.chat.manage"
  chat-closed-bypass: "akyto.chat.closed.bypass"
  freeze: "akyto.staff"
  modmode: "akyto.staff"
  disguise: "akyto.disguise"

broadcast-settings:
  rank-promote: true
  rank-demote: true
  banAnnounce: true
  muteAnnounce: true
  warnAnnounce: true
  try-to-connect-notifications: true
  staff-proxy-notification: true

messages:
  namemc-unliked: "&7Want to support us? Like the server on NameMC: &fhttps://fr.namemc.com/server/akyto.club"
  namemc-liked: "&7Thank you for your &alike!"
  private-message: "&7(%incommingType% %rank%%rankColor%%player%&7) &e%message%"
  time: "&fTime changed to: &c%time%"
  modmode: "%type% staffmode&7, &fif you want %subType% it &7(/mod)"
  frozed: "&fYou are currently frozen by &c%frozer%"
  frozeStatusNotif: "&fFrozen status of &e%frozed% &fhas been updated to &c%frozeStatus%&f!"
  chatPriorityChanged: "&fThe chat priority has been updated to &c%priority%"
  chatOpenned: "&aThe chat is now available."
  chatClosed: "&cThe chat is now temporarily closed."
  banAnnounce: "&4%banned% &8has been suspended from the network."
  unbanAnnounce: "&4%banned% &8is now unbanned."
  muteAnnounce: "&4%muted% &8is now muted."
  unmuteAnnounce: "&4%muted% &8is no longer muted."
  muteCancel: "&8You cannot write in chat. Your right has been revoked for the following reasons &c%reason%&8."
  banTryConnect: "&c%banned% &7tried to join the server while being banned. Expires in: &c%expires%"
  banDisconnect: "&cYou've been suspend on Akyto\n&7Reason: &4%reason%\n&7Author: &e%judge%\n&7Expires on: &c%expires%\n\n&7Appeal on: &f.gg/nMwn5pTbxF"
  noPermission: "&cYou don't have the required permissions."
  alreadyExist: "&cThe %value% %type% already exist"
  created: "&aSuccesfully created %value% %type%" 
  deleted: "&cSuccesfully deleted %value% %type%"
  notExist: "&c%value%'s %type% does not exist!"
  edited: "&a%key% %type% as %editType% to %value%"
  alreadySet: "&cThis %value% is already setted"
  staff-proxy-notification: "&7[&eStaff&7] %rank% %rankColor%%player% &fhas %type% the server!"
  server-restart: "&cAkyto is going to reboot!"
  neverPlayed: "&c%target%'s never played on the network."
  rank-promote: "&a%target% &8is promoted to &c%rankUp%"
  rank-demote: "&c%target% &8has been demoted."
  banHelp:
    - "&7&m----------------------"
    - "&8/ban <player> <time> <reason>"
    - "&8/ban info <player>"
    - "&8/unban <player>"
    - "&7&m----------------------"
  muteHelp:
    - "&7&m----------------------"
    - "&8/mute <player> <time> <reason>"
    - "&8/mute info <player>"
    - "&8/mute <player>"
    - "&7&m----------------------"
  punishmentInformations:
    - "&7&m----------------------"
    - "&8Username&7: &f%user% &7- &4%punishmentType%"
    - "&8Expires On&7: &c%expires%"
    - "&8Reason&7: &e%reason%"
    - "&8Author&7: &6%judge%"
    - "&7&m----------------------"
  rankHelp:
    - "&7&m----------------------"
    - "&8/rank create <name>"
    - "&8/rank setprefix <name> <prefix>"
    - "&8/rank settype <name> <COMMUNITY/MODERATION/ADMIN>"
    - "&8/rank setcolor <name> <color>"
    - "&8/rank addperm <rank> <perm>"
    - "&8/rank delperm <rank> <perm>"
    - "&8/rank delete <name>"
    - " "
    - "&8/rank promote <player> <rank>"
    - "&8/rank demote <player>"
    - "&7&m----------------------"
  randomTeleport: 
    - "&7Successfuly teleported to &c%target%"
    - "&7&m------------------------------------"
    - "&eMatch Informations&7:"
    - "&a%playerOne% &7against &c%playerTwo%"
    - "&fDuration&7: &e%matchDuration%"
    - "&fKit&7: &e%matchLadder%"
    - "&7&m------------------------------------"