name: Core
author: [kezukdev]
version: 1.0
main: gym.core.Core
commands:
  rank:
    aliases: [ranks, grade]
  ban:
    aliases: [bans, banning]
  unban:
    aliases: [unbans, deban, unbanning]
  mute:
    aliases: [mutes, muted]
  unmute:
    aliases: [demute, unmuted, unmutes]
  warn:
    aliases: [warned, warns, warning]
  viewcps:
    aliases: [verif, sscps, cpsview, ss]
  chat:
  freeze:
    aliases: [froze, frozed, freezed, frozen, ss]